Add shrink_iri function
endoli/curie.rs pull request #3
Opened 2018-06-19 13:25 UTC by phillord

Something like this perhaps (will add documentation if you are broadly happy).

I am not sure about the handling of the default case, because I am returning "" when I really mean `None`. It's not easy to fit this into the `Curie` interface. The alternative is just to return a string.

2018-06-19 14:52 UTC, waywardmonkeys requested changes
What is supposed to happen if there are multiple matching prefixes?

And yeah, we will need to fix Curie to handle default vs empty prefix... but that can be a separate change.

Adding docs would pretty much finish this up!

Could you also run rustfmt on this? (if not, I can after it lands...)

2018-06-19 14:52 UTC, waywardmonkeys commented on src/lib.rs
> +#[derive(Eq,PartialEq,Debug)]
Alphabetize the derives, please.

2018-07-02 21:15 UTC, phillord commented
Your question about multiple matching prefixes rather stumped me. As far as I can tell, it doesn't say in the spec. The current solution is arbitrary, depending on `HashMap` iterator order.

Think I have done the rest -- didn't know about `rustfmt` so I've learned something there.

2018-07-06 04:40 UTC, waywardmonkeys approved these changes

2018-07-06 04:41 UTC, waywardmonkeys commented
Thanks! I've sort of been on holiday lately ... but this looks good and I'll land it now.

2018-07-06 04:41 UTC, merged

2018-07-06 04:45 UTC, waywardmonkeys commented
I've published `0.0.7` with this now.

2018-07-06 21:01 UTC, phillord commented
Thanks! No worries about the delay and I hope that you are enjoying the holiday.